CREATE TABLE EMP1(
    ENAME VARCHAR2(20),
    ECITY VARCHAR2(20),
    ENUMBER INTEGER PRIMARY KEY,
    EADDRESS VARCHAR2(20),
    DEPTTNAME VARCHAR2(20)
);

CREATE TABLE COMPANY(
CNAME VARCHAR2(20),
CCITY VARCHAR2(20),
EMPNUMBER INTEGER
);
