SET SERVEROUTPUT ON;

DECLARE
    NUM1   NUMBER;
    NUM2   NUMBER;
    RESULT NUMBER;
BEGIN
    NUM1 :=&NUM1;
    NUM2:= &NUM2;
    RESULT :=NUM1/NUM2;
    DBMS_OUTPUT.PUT_LINE('RESULT : '
                         ||RESULT);
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('DIVISION BY ZERO NOT POSSIBLE.');
END;
/