DECLARE
    REV  INTEGER :=0;
    NUM  INTEGER;
    REM INTEGER;
    TEMP INTEGER;
BEGIN
    NUM:=&NUM;
    TEMP := NUM;
    WHILE NUM > 0 LOOP
        REM :=MOD(NUM, 10);
        REV := (REV*10)+REM;  
        NUM := TRUNC(NUM/10);
    END LOOP;
    IF(REV = TEMP) THEN
        DBMS_OUTPUT.PUT_LINE('THE ENTERED NUMBER IS A PALINDROME.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('THE ENTERED NUMBER IS NOT A PALINDROME.');
    END IF;
END;